@startuml Cooling Process
!define ICONURL https://www.plantuml.com/plantuml/img/
!define ICON(IMG) <img:ICONURLIMG>
!define HEADER ICON(activity/activity.png)

(*) --> "Refrigerator: Monitor Temperature"
  --> "Refrigerator: Get Current Temperature"
  --> "Refrigerator: Check Temperature Against SetPoint"
  --> if "Temperature > SetPoint" then
      -->[true] "Refrigerator: Cooling Process"
        --> "Compressor: Start Compressing"
        --> "Refrigerator: Absorb Heat"
        --> "Refrigerator: Circulate Refrigerant"
        --> "Condenser: Release Heat"
        --> while "Temperature > SetPoint" is true
            --> "Refrigerator: Monitor and Check Temperature Against SetPoint"
            --> if "Temperature <= SetPoint" then
                  -->[true] "Refrigerator: Continue Cooling"
                  --> "Compressor: Continue Compressing"
              --> else
                  -->[false] "Refrigerator: Stop Cooling"
                  --> "Compressor: Stop Compressing"
                  --> "Refrigerator: Cooling Completed"
              --> endif
        --> endwhile
    else
      -->[false] "Refrigerator: No Cooling Needed"
    endif
@enduml